<a href="https://colab.research.google.com/github/carwilfer/Projeto-IoT-e-Data-Science/blob/main/tree/main/Docs/DataReport/PB_DQRS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import pytz

In [15]:
df_NYC_Motor = pd.read_csv('NYC_Motor.csv')
df_NYC_Motor

,CRASH_DATE,CRASH_TIME,PERSON_INJURY,PERSON_AGE,BODILY_INJURY,SAFETY_EQUIPMENT,PERSON_SEX,PERSON_TYPE,PED_LOCATION,CONTRIBUTING_FACTOR_2,...,COMPLAINT,EMOTIONAL_STATUS,VEHICLE_ID,PERSON_ID,CONTRIBUTING_FACTOR_1,POSITION_IN_VEHICLE,PED_ROLE,UNIQUE_ID,PED_ACTION,COLLISION_ID
0,2021-05-02,21:00,Killed,62.0,Head,NaN,F,Pedestrian,Pedestrian/Bicyclist/Other Pedestrian at Inter...,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,...,Severe Bleeding,Apparent Death,NaN,f2f329b6-2dfc-4bd0-b751-2e4255f1ea06,Traffic Control Disregarded,NaN,Pedestrian,11791937,Crossing Against Signal,4412948
1,2021-05-21,0:00,Killed,24.0,Entire Body,Air Bag Deployed,M,Occupant,NaN,NaN,...,Internal,Apparent Death,19986231.0,e27e12a2-0485-4e22-b692-3f8a765d2582,NaN,Driver,Driver,11819198,NaN,4419608
2,2021-10-15,2:00,Killed,30.0,Head,None,M,Occupant,NaN,NaN,...,Internal,Apparent Death,20091024.0,1a6f5aa7-5125-4be2-8499-fe7977cb0d90,NaN,Driver,Driver,11998317,NaN,4467504
3,2021-04-17,13:00,Killed,71.0,Head,NaN,M,Pedestrian,Pedestrian/Bicyclist/Other Pedestrian Not at I...,Unspecified,...,Internal,Unconscious,NaN,b950706b-00a4-485c-84c5-777208cc3cc9,Pedestrian/Bicyclist/Other Pedestrian Error/Co...,NaN,Pedestrian,11745791,"Crossing, No Signal, or Crosswalk",4408062
4,2021-05-25,22:00,Killed,69.0,Entire Body,NaN,F,Pedestrian,Pedestrian/Bicyclist/Other Pedestrian Not at I...,Unspecified,...,None Visible,Conscious,NaN,6504ea0a-c92d-444c-8127-284943be9aac,Unspecified,NaN,Pedestrian,11991283,"Crossing, No Signal, Marked Crosswalk",4420918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45664,2021-05-07,0:00,Injured,24.0,Back,Lap Belt & Harness,M,Occupant,NaN,NaN,...,Complaint of Pain or Nausea,Conscious,19988552.0,051c2721-1533-4f48-bda4-273bd3725242,NaN,Driver,Driver,11823105,NaN,4414130
45665,2021-04-27,13:00,Injured,29.0,Knee-Lower Leg Foot,Lap Belt & Harness,M,Occupant,NaN,NaN,...,Complaint of Pain or Nausea,Conscious,19966687.0,017e3824-4cbe-409a-ba57-e741923a60a1,NaN,Driver,Driver,11785808,NaN,4411119
45666,2021-05-07,14:00,Injured,7.0,Head,Child Restraint Only,F,Occupant,NaN,NaN,...,Complaint of Pain or Nausea,Conscious,19951136.0,c70e93ff-cb5f-4e15-b888-0f17a1ede0cd,NaN,"Left rear passenger, or rear passenger on a bi...",Passenger,11758963,NaN,4415414
45667,2021-05-10,16:00,Injured,13.0,Elbow-Lower-Arm-Hand,None,F,Occupant,NaN,NaN,...,Complaint of Pain or Nausea,Conscious,19991766.0,bb039a41-8563-493b-9fd1-a5bcd15fbb33,NaN,Right rear passenger or motorcycle sidecar pas...,Passenger,11828495,NaN,4415201
45668,2021-11-09,13:00,Injured,29.0,Shoulder - Upper Arm,Lap Belt & Harness,M,Occupant,NaN,NaN,...,None Visible,Conscious,20109461.0,8fc5e0f7-66da-4e62-b7f1-a0e8dbdb0ea6,NaN,"Left rear passenger, or rear passenger on a bi...",Passenger,12030648,NaN,4476118

In [16]:
df_NYC_Motor.describe()

         PERSON_AGE    VEHICLE_ID     UNIQUE_ID  COLLISION_ID
count  45248.000000  3.909800e+04  4.566900e+04  4.566900e+04
mean      37.487646  1.999663e+07  1.183588e+07  4.431737e+06
std       81.492032  7.940981e+04  1.375828e+05  2.753403e+04
min     -971.000000  1.982197e+07  1.153725e+07  4.380715e+06
25%       25.000000  1.996078e+07  1.177289e+07  4.408781e+06
50%       34.000000  2.000877e+07  1.185680e+07  4.432358e+06
75%       48.000000  2.005868e+07  1.194421e+07  4.455395e+06
max     9999.000000  2.010992e+07  1.203146e+07  4.478832e+06

In [17]:
df_NYC_Motor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45669 entries, 0 to 45668
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CRASH_DATE             45669 non-null  object
 1   CRASH_TIME             45669 non-null  object
 2   PERSON_INJURY          45669 non-null  object
 3   PERSON_AGE             45248 non-null  float64
 4   BODILY_INJURY          45669 non-null  object
 5   SAFETY_EQUIPMENT       39434 non-null  object
 6   PERSON_SEX             45669 non-null  object
 7   PERSON_TYPE            45669 non-null  object
 8   PED_LOCATION           6571 non-null   object
 9   CONTRIBUTING_FACTOR_2  6546 non-null   object
 10  EJECTION               39429 non-null  object
 11  COMPLAINT              45669 non-null  object
 12  EMOTIONAL_STATUS       45669 non-null  object
 13  VEHICLE_ID             39098 non-null  float64
 14  PERSON_ID              45669 non-null  object
 15  CONTRIBUTING_FACTOR_1  6558 non-null   object
 16  POSITION_IN_VEHICLE    39448 non-null  object
 17  PED_ROLE               45669 non-null  object
 18  UNIQUE_ID              45669 non-null  int64
 19  PED_ACTION             6571 non-null   object
 20  COLLISION_ID           45669 non-null  int64
dtypes: float64(2), int64(2), object(17)
memory usage: 7.3+ MB

In [18]:
df_NYC_Motor.columns

Index(['CRASH_DATE', 'CRASH_TIME', 'PERSON_INJURY', 'PERSON_AGE',
       'BODILY_INJURY', 'SAFETY_EQUIPMENT', 'PERSON_SEX', 'PERSON_TYPE',
       'PED_LOCATION', 'CONTRIBUTING_FACTOR_2', 'EJECTION', 'COMPLAINT',
       'EMOTIONAL_STATUS', 'VEHICLE_ID', 'PERSON_ID', 'CONTRIBUTING_FACTOR_1',
       'POSITION_IN_VEHICLE', 'PED_ROLE', 'UNIQUE_ID', 'PED_ACTION',
       'COLLISION_ID'],
      dtype='object')

In [19]:
df_NYC_Motor.columns.values

array(['CRASH_DATE', 'CRASH_TIME', 'PERSON_INJURY', 'PERSON_AGE',
       'BODILY_INJURY', 'SAFETY_EQUIPMENT', 'PERSON_SEX', 'PERSON_TYPE',
       'PED_LOCATION', 'CONTRIBUTING_FACTOR_2', 'EJECTION', 'COMPLAINT',
       'EMOTIONAL_STATUS', 'VEHICLE_ID', 'PERSON_ID',
       'CONTRIBUTING_FACTOR_1', 'POSITION_IN_VEHICLE', 'PED_ROLE',
       'UNIQUE_ID', 'PED_ACTION', 'COLLISION_ID'], dtype=object)

In [20]:
df_NYC_Motor.isnull().sum()
# as seguintes variaveis tem dados faltantes...

CRASH_DATE                   0
CRASH_TIME                   0
PERSON_INJURY                0
PERSON_AGE                 421
BODILY_INJURY                0
SAFETY_EQUIPMENT          6235
PERSON_SEX                   0
PERSON_TYPE                  0
PED_LOCATION             39098
CONTRIBUTING_FACTOR_2    39123
EJECTION                  6240
COMPLAINT                    0
EMOTIONAL_STATUS             0
VEHICLE_ID                6571
PERSON_ID                    0
CONTRIBUTING_FACTOR_1    39111
POSITION_IN_VEHICLE       6221
PED_ROLE                     0
UNIQUE_ID                    0
PED_ACTION               39098
COLLISION_ID                 0
dtype: int64

In [21]:
df_NYC_Motor.isna().sum()

CRASH_DATE                   0
CRASH_TIME                   0
PERSON_INJURY                0
PERSON_AGE                 421
BODILY_INJURY                0
SAFETY_EQUIPMENT          6235
PERSON_SEX                   0
PERSON_TYPE                  0
PED_LOCATION             39098
CONTRIBUTING_FACTOR_2    39123
EJECTION                  6240
COMPLAINT                    0
EMOTIONAL_STATUS             0
VEHICLE_ID                6571
PERSON_ID                    0
CONTRIBUTING_FACTOR_1    39111
POSITION_IN_VEHICLE       6221
PED_ROLE                     0
UNIQUE_ID                    0
PED_ACTION               39098
COLLISION_ID                 0
dtype: int64